### ISSUE TITLE
Android Studio can not add ：com.microsoft.projectoxford:speechrecognition:2.1.0

### ISSUE THREAD

**Issue by wxyaus** [Microsoft/Cognitive-Speech-STT-Android#13]

**Comment by cuongtructran** [comment]
The latest version is 1.1.0. 
I don't know why they put in version 2.1.0.

**Comment by jasonvomsft** [comment]
@wxyaus please confirm you are using 1.1.0.  As @cuongtructran mentioned we do not have version 2.1.0

**Comment by lsc4719** [comment]
What the...
