### ISSUE TITLE
NullPointerException when trying to send audio via DataRecognitionClient

### ISSUE THREAD

**Issue by ynop** [Microsoft/Cognitive-Speech-STT-Android#14]
I'm trying to use the DataRecognitionClient to transcribe audio from a wav file. When i try to send the audio data i'm getting the following error:

>12-21 10:18:05.870 4812-4812/? I/MonitoringInstrumentation: Activities that are still in CREATED to STOPPED: 0
12-21 10:18:05.877 4812-4827/? W/linker: /data/app/ch.path.android-1/lib/x86/libandroid_platform.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
12-21 10:18:05.881 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.884 4812-4827/? I/NLPLAT: Application Name: 
12-21 10:18:05.885 4812-4827/? I/NLPLAT: Initializing Audio Services
12-21 10:18:05.885 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.885 4812-4827/? W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
12-21 10:18:05.888 4812-4827/? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
12-21 10:18:05.890 4812-4827/? W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 16000 Hz, output 44100 Hz
12-21 10:18:05.890 1305-3051/? W/AudioFlinger: createTrack_l(): mismatch between requested flags (00000100) and output flags (00000002)
12-21 10:18:05.891 4812-4827/? D/AudioTrack: Client defaulted notificationFrames to 250 for frameCount 750
12-21 10:18:05.892 4812-4827/? I/NLPLAT: Initializing Speech Services
12-21 10:18:05.892 4812-4827/? I/NLPLAT: Failed to 'pProperties->ReadProperty(L"ServiceUri", connectionUrlVar)', HR=80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? I/NLPLAT: originating error 0x80070057
12-21 10:18:05.892 4812-4827/? W/art: Attempt to remove non-JNI local reference, dumping thread
12-21 10:18:05.892 4812-4827/? W/art: Attempt to remove non-JNI local reference, dumping thread
12-21 10:18:05.926 4812-4828/? I/NLPLAT: ImpressionId: S
12-21 10:18:05.926 4812-4828/? W/art: Attempt to remove non-JNI local reference, dumping thread
12-21 10:18:05.926 4812-4828/? I/NLPLAT: originating error 0x8000ffff
12-21 10:18:05.926 4812-4828/? I/NLPLAT: originating error 0x8000ffff
12-21 10:18:05.926 4812-4828/? I/NLPLAT: Unable to create native AudioStream.
                                                                               --------- beginning of crash
12-21 10:18:05.926 4812-4828/? E/AndroidRuntime: FATAL EXCEPTION: SpeechRecognitionService Background Worker Thread
                                                 Process: ch.path.android, PID: 4812
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.bing.speech.AudioStream.write(byte[], int, int)' on a null object reference
                                                     at com.microsoft.cognitiveservices.speechrecognition.DataRecognitionClient.sleepAndSendAudioWorker(DataRecognitionClient.java:196)
                                                     at com.microsoft.cognitiveservices.speechrecognition.DataRecognitionClient.access$100(DataRecognitionClient.java:19)
                                                     at com.microsoft.cognitiveservices.speechrecognition.DataRecognitionClient$2.run(DataRecognitionClient.java:102)
                                                     at com.microsoft.cognitiveservices.speechrecognition.WorkQueue.threadWorker(WorkQueue.java:64)
                                                     at com.microsoft.cognitiveservices.speechrecognition.WorkQueue$1.run(WorkQueue.java:31)
12-21 10:18:05.927 4812-4828/? I/Process: Sending signal. PID: 4812 SIG: 9

Code:
```kotlin
var client = SpeechRecognitionServiceFactory.createDataClient(SpeechRecognitionMode.ShortPhrase, "de-DE", this, SUBSCRIPTION_KEY)

client.sendAudio(item.toByteArray(), item.size())
```

Native Libraries (libandroid_platform.so) are included and dependency defined:
```
sourceSets {
        main {
            jniLibs.srcDir 'src/main/jniLibs'
        }
}
```

```
compile 'com.microsoft.projectoxford:speechrecognition:1.1.0'
```
Same issue with emulator and real device.

**Comment by xuangong** [comment]
Failed to 'pProperties->ReadProperty(L"ServiceUri", connectionUrlVar)', HR=80070057
At least this error is caused by proguard, add the native library and jar package in whitelist of proguard rule configure.
-keepclassmembers class * { native <methods>; }
-keep class com.microsoft.projectoxford.** { *; }

**Comment by jasonvomsft** [comment]
@ynop, I agree with @xuangong 's assessment.  Please confirm you have the correct progaurd settings.  Feel free to reopen if you still run into issues.
