### ISSUE TITLE
End of speech indication

### ISSUE THREAD

**Issue by harshithagb** [Microsoft/Cognitive-Speech-STT-Android#20]
I want to continuously stream the live audio(microphone input) to the REST API while the user is speaking. 
It is mentioned that API doesn't accept more than 10 seconds audio in one request and we should indicate start and end of speech to the API.

Problem:
How do indicate end of speech to the API?

**Comment by priyaravi20** [comment]
REST API does not support endpointing. Please use one of our client libraries for more control an dlonger audio transcription.
