### ISSUE TITLE
Android Speech API LongDictation dutch language returns without translation

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-Android#3]
_From @Marc1510 on April 4, 2016 13:57_

I'm using the [Speech to text Android SDK](https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/Speech/SpeechToText/Android) with the sample application. However as the documentation says it should support the language dutch. So I changed the `getDefaultLocale()` to return 'nl-NL'. When the language code has changed the complete recognition stops. On the screen is visible that it did start with LongDictation recognition but the next message is **\* Final n-BEST Results ***' without any result. The ShortDictation does work with the dutch language for some reason.

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#43_

**Comment by margaretmz** [comment]
_From @doplumi on April 5, 2016 9:26_

On the web version of the library the input is all lowercase, like "nl-nl". Maybe here it's also is the case. Have you tried that?

**Comment by margaretmz** [comment]
_From @Marc1510 on April 5, 2016 11:53_

@domtallo I have tried that but it also returns immediately. However for short dictation it does work.

**Comment by priyaravi20** [comment]
This has been fixed.
